version: "3"

services:
    postgres:
        image: postgres:16
        container_name: flamespa-postgresql
        environment:
            POSTGRES_DB: flamespa
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
        ports:
            - "5432:5432"
        volumes:
            - ./postgresql:/var/lib/postgresql/data
    redis:
        image: redis:6
        container_name: flamespa-redis
        ports:
            - "6379:6379"
